#!/bin/bash

path=$1
user=`whoami`

echo "Setting owner '$user' and group 'www-data'..."
sudo chown $user.www-data -R $path

echo "Setting files permissions to 660..."
sudo chmod 660 -R $path

echo "Setting directories permissions to 770..."
sudo find -type d -exec chmod 770 {} \;

if [ -f devtools/build.sh ]
then
	chmod +x devtools/build.sh
fi

echo "Done"

