#!/bin/bash

path="$(dirname $0)"

mkdir -p  ~/.config/sublime-text-2/Packages/User/
cp $path/home/* ~/

function install() {
	target=$1
	file=$2

	if [ ! -d "$target" ]
	then
		sudo mkdir -p "$target"
	fi

	sudo cp "$path/$target/$file" "$target"
}


install /etc/subversion config
install /etc/vim vimrc
install /usr/share/vim/vim73/syntax dart.vim

sudo bash -c "cat $path/usr/share/vim/vim73/filetype.dart.vim >> /usr/share/vim/vim73/filetype.vim"
